DROP TABLE IF EXISTS products;
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR (255) NOT NULL,
    description VARCHAR (255),
    price DECIMAL (19,2) NOT NULL,
    image_url VARCHAR (255),
    stock_quantity INTEGER NOT NULL,
    category VARCHAR (255)
);